name: 'Configure Git'
description: 'Configure git user for YDB CLI releases'
runs:
  using: 'composite'
  steps:
    - name: Configure git
      shell: bash
      run: |
        git config --global user.email github-actions@github.com
        git config --global user.name "GitHub Actions"
